# Generated by Django 4.1.1 on 2022-11-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairoil', '0003_payment_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_tb',
        ),
    ]
