# Generated by Django 4.1.1 on 2022-11-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairoil', '0004_delete_payment_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productup',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
